# Generated by Django 3.2.8 on 2021-10-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
