# Generated by Django 3.2.8 on 2021-10-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_post_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main_app.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
