# Generated by Django 3.2.8 on 2021-10-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_email'),
        ('main_app', '0007_auto_20211017_1503'),
    ]

    operations = [
    ]
