# Generated by Django 3.2.8 on 2021-10-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_0003_profile_email_0007_auto_20211017_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='null', upload_to='media/'),
            preserve_default=False,
        ),
    ]
