# Generated by Django 3.2.8 on 2021-10-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.FileField(default='null', upload_to='profile/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='null', upload_to='post/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='profile/'),
        ),
    ]
