# Generated by Django 3.2.8 on 2021-10-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main_app.profile'),
        ),
    ]
