# Generated by Django 3.2.8 on 2021-10-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20211019_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='./static/images/london-eye.jpeg', null=True, upload_to='profile/'),
        ),
    ]
