# Generated by Django 3.2.8 on 2021-10-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('1', 'SAN FRANSICO, CA'), ('2', 'LOS ANGELES, CA'), ('3', 'CHICAGO, IL'), ('4', 'HOUSTON, TX'), ('5', 'PHOENIX, AZ')], default='1', max_length=50),
        ),
    ]
