# Generated by Django 3.2.8 on 2021-10-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('SAN FRANSICO, CA', 'SAN FRANSICO, CA'), ('NEW YORK, NY', 'NEW YORK, NY')], default='1', max_length=50),
        ),
    ]
