# Generated by Django 3.2.8 on 2021-10-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20211020_0349'),
        ('main_app', '0018_auto_20211020_0355'),
    ]

    operations = [
    ]
