# Generated by Django 3.2.8 on 2021-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
