# Generated by Django 3.2.8 on 2021-10-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='city/'),
        ),
    ]
