# Generated by Django 3.2.8 on 2021-10-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_post_description'),
        ('main_app', '0024_alter_profile_slug'),
    ]

    operations = [
    ]
